### ISSUE TITLE
升级思源2.8.8后，配置的颜色全部消失

### ISSUE THREAD

**Issue by yanyu2015** [zxhd863943427/siyuan-color-scheme#1]
是每次升级配置都会被覆盖，需要重新上传，还是说当前的版本没设计这功能，或者说，是个bug?

**Comment by zxhd863943427** [comment]
这是2.8.8思源接口的bug，新版本的插件已经绕过修复，不过2.8.9的思源也修复了这个bug，不知道这个插件的绕过修复需不需要取消，这样就得重新导入一遍配置……
