### ISSUE TITLE
暗色配色文件上传后菜单中不显示

### ISSUE THREAD

**Issue by git-zxx** [zxhd863943427/siyuan-color-scheme#3]
![image](https://github.com/zxhd863943427/siyuan-color-scheme/assets/42286494/45b538bd-9f5a-448d-a89d-d15745e084f9)
如图，暗色菜单里展开看不到上传的配色文件（在暗色主题环境上传后仍然看不到）

**Comment by zxhd863943427** [comment]
暗色配色方案的上传不是在暗色主题环境下上传，而是在配置文件里填写这部分：
![图片](https://github.com/zxhd863943427/siyuan-color-scheme/assets/74853597/ee53cf5a-94dd-414b-98b2-721378bce389)

也就是说，允许一份配色方案提供亮色和暗色两套模式。

对于你的情况，将light改为dark即可。

**Comment by git-zxx** [comment]
嗷嗷谢谢😁
