### ISSUE TITLE
Bug：暗色模式下不生效

### ISSUE THREAD

**Issue by git-zxx** [zxhd863943427/siyuan-color-scheme#5]
主题：Savor
暗色主题中的自定义样式不生效。
上传的json文件是同时包含了light和dark数据的（json代码中的dark部分是手动复制进去的）
![image](https://github.com/zxhd863943427/siyuan-color-scheme/assets/42286494/42c71333-51b3-4343-827f-77420888be5f)
我重新上传这个json也只是亮色主题生效
大佬有时间看一下🙏🙏🙏

**Comment by zxhd863943427** [comment]
这是一个bug，最新版会修复。
